### ISSUE TITLE
When DELETE user role only with role_id get 204

### ISSUE THREAD

**Issue by ivchenkodima** [edenlabllc/mithril.api#62]
api/admin/users/undefined/roles/38d10313-541e-42cc-acc5-d764fced46c0

**Comment by gmile** [comment]
@ivchenkodima why do you get `undefined` in place where `user_id` must be present? Do you not have the info about the user you're removing the role from?

**Comment by AlexKovalevych** [comment]
@gmile as discussed with @lymychp we're not using `user_id` from the url so i've removed it in my PR

**Comment by gmile** [comment]
I merged the PR.

But where can I see some context on this? We still have URLs left that rely on `user_id`:

```
GET /admin/users/:user_id/roles
POST /admin/users/:user_id/roles
```
