### ISSUE TITLE
old app:authorize access tokens should expire on renewal procedure

### ISSUE THREAD

**Issue by pzhuk** [edenlabllc/mithril.api#84]
So I have tried to generate sequentially multiple access_tokens on app:authorize scope.
Each time new token is getting generated with is correct.
However, even when new token is generated - old one is still available and could be exchanged to authorize scopes futher tokens manipulation.

As soon as we do not have logout procedure for the user, we have to expire all previous access_tokens when new one is created

How to reproduce:

Request:

```
POST /oauth/tokens HTTP/1.1
Host: demo.ehealth.world
Content-Type: application/json
Cache-Control: no-cache
Postman-Token: 8321e6bf-c679-047c-11a4-4601d7f7ea2f

{
   "token":{
      "grant_type":"password",
      "email":"sp.virny+100@gmail.com",
      "password":"12345678",
      "client_id":"e2e1d2c8-9bac-43c6-adef-83239940b30a",
      "scope":"app:authorize"
   }
}
```

Response:

```
{
  "meta": {
    "url": "http://demo.ehealth.world/oauth/tokens",
    "type": "object",
    "request_id": "gev4okl7egei20mihuglkdnotbvan1kj",
    "code": 201
  },
  "data": {
    "value": "S0RpVDZpdDA5YXRDUzc4dmtUbHlKdz09",
    "user_id": "3a333f3c-7051-4f33-978d-974153cb4bb7",
    "name": "access_token",
    "id": "feb20a23-83d9-4ac6-808c-23389a9cc088",
    "expires_at": 1501801495,
    "details": {
      "scope": "app:authorize",
      "redirect_uri": "*.example.com",
      "grant_type": "password",
      "client_id": "e2e1d2c8-9bac-43c6-adef-83239940b30a"
    }
  }
}
```

Repeat this calls multiple times to ensure that new authorization access codes were created.
Try to perform scopes authorization with the authorization string from the very first call - and it works. So tokens are not getting auto-experied on issuing new one

```
POST /oauth/apps/authorize HTTP/1.1
Host: demo.ehealth.world
Content-Type: application/json
Authorization: Bearer S0RpVDZpdDA5YXRDUzc4dmtUbHlKdz09
Cache-Control: no-cache
Postman-Token: 8e8c5d07-af6a-186c-e119-b0c7e3dae8e6

{
   "app":{
      "client_id":"786d84d9-e1c5-4d58-9f0f-f5f3d826b26e",
      "redirect_uri":"http://example2.com",
      "scope":"employee_request:write"
   }
}

```

Response:
```

{
  "meta": {
    "url": "http://demo.ehealth.world/oauth/apps/authorize",
    "type": "object",
    "request_id": "dvkcinqtj0dvoog2qv9onse5gqvgcmi5",
    "code": 201
  },
  "data": {
    "value": "K0x6dGZaYkk5V0JGMHptTStlR3c5QT09",
    "user_id": "3a333f3c-7051-4f33-978d-974153cb4bb7",
    "name": "authorization_code",
    "id": "e6904b5e-4ca2-45c9-918d-aec7c3a78126",
    "expires_at": 1499210160,
    "details": {
      "scope": "app:authorize",
      "redirect_uri": "http://example2.com",
      "grant_type": "password",
      "client_id": "786d84d9-e1c5-4d58-9f0f-f5f3d826b26e"
    }
  }
}

```

**Comment by pzhuk** [comment]
@lymychp  how about this one?

**Comment by TarasenkoA** [comment]
Create new access token - OEl6eVFaWEthQVZaNlBuTE4rOEx6QT09
and test service - `http://dev.ehealth.world/api/legal_entities` - code 200 in response, it's OK.
"request_id": "jvn64ipkpj6dlqk7gu1an4ro5skipmrg"

When I try to create another access token - Uis2WTFaeVk2MEd3RE9NMWZ0L2x1dz09
and test service - `http://dev.ehealth.world/api/legal_entities`with previously access token - have code 200 in response, it's incorrectly - old token must expired after generate new
"request_id": "rkd57fuh156g4o07jgp3gu77a1vfahqm"
